---
driver:
  name: scalr
  require_chef_omnibus: 13.4.19

provisioner:
  name: chef_zero
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
    driver:
      scalr_api_key_id: 'APIKLMM2GHBHUEFFESFQ'
      scalr_api_key_secret: 'wkffJ8uDx+MgQtPKWd8ZPNeC7r5lo11UuXq9NwzQ'
      scalr_api_url: 'http://demo.scalr.com'
      scalr_env_id: '53'
      scalr_project_id: '75c84cfe-c5e8-4fc4-b1e4-e68665a4a30c'
      scalr_server_instanceType: 'm3.medium'
      scalr_use_role: 82948
      scalr_platform: 'ec2'
      scalr_location: 'us-west-1'
      scalr_base_farm_role:
        security:
          securityGroups:
            - id: 'sg-00bfcf79'
        networking:
          networks:
            - id: 'vpc-9483dcf1'
          subnets:
            - id: 'subnet-26adbd43'

suites:
  - name: default
    run_list:
      - recipe[scalr-jenkins::default]
    attributes:
